/**
 * Where an event can gather, for the "Punto di ritrovo sulla mappa" picker in
 * `keystatic.config.ts`.
 *
 * GENERATED by scripts/build-site-options.mjs. Do not edit: the list is the
 * landings and points of interest in src/content/map-features.
 */
export const MEETING_POINT_OPTIONS = [
  { label: 'Atterraggio Bagnolo', value: 'atterraggio-bagnolo' },
  { label: 'Atterraggio Beba', value: 'atterraggio-beba' },
  { label: 'Atterraggio Blancio', value: 'atterraggio-blancio' },
  { label: 'Atterraggio Castel del Bosco', value: 'atterraggio-castel-del-bosco' },
  { label: 'Atterraggio Chambons', value: 'atterraggio-chambons' },
  { label: 'Atterraggio Inverso Pinasca', value: 'atterraggio-inverso-pinasca' },
  { label: 'Atterraggio Malzat', value: 'atterraggio-malzat' },
  { label: 'Atterraggio Podio', value: 'atterraggio-podio' },
  { label: 'Atterraggio Pomarretto', value: 'atterraggio-pomarretto' },
  { label: 'Atterraggio Ponte di Bibiana', value: 'atterraggio-ponte-di-bibiana' },
  { label: 'Atterraggio Pourrieres', value: 'atterraggio-pourrieres' },
  { label: 'Atterraggio Roletto', value: 'atterraggio-roletto' },
  {
    label: 'Atterraggio Strada Provinciale Bobbio',
    value: 'atterraggio-strada-provinciale-bobbio',
  },
  { label: 'Parcheggio Roletto', value: 'parcheggio-roletto' },
  { label: 'Ritrovo: Parcheggio Eataly', value: 'ritrovo-parcheggio-eataly' },
  { label: 'Ritrovo: Ponte di Bibiana', value: 'ritrovo-ponte-di-bibiana' },
  { label: 'Ritrovo: Villa Glicini', value: 'ritrovo-villa-glicini' },
] as const;
