/**
 * The flight sites, for the "Sito di volo" picker in `keystatic.config.ts`.
 *
 * GENERATED by scripts/build-site-options.mjs. Do not edit: add, rename or
 * remove a site in src/content/sites and the next build rewrites this.
 */
export const SITE_OPTIONS = [
  { label: "Bourcet", value: "bourcet" },
  { label: "Colle Lazzarà", value: "colle-lazzara" },
  { label: "Forte di Fenestrelle", value: "forte-di-fenestrelle" },
  { label: "Le Grange", value: "le-grange" },
  { label: "Monte Cucetto", value: "monte-cucetto" },
  { label: "Monte Freidur", value: "monte-freidur" },
  { label: "Montoso", value: "montoso" },
  { label: "Pian dell'Alpe", value: "pian-dellalpe" },
  { label: "Podio", value: "podio" },
  { label: "Prali", value: "prali" },
  { label: "Punta Ceresa", value: "punta-ceresa" },
  { label: "Roletto", value: "roletto" },
  { label: "Sarsenà", value: "sarsena" },
  { label: "Sea di Torre", value: "sea-di-torre" },
] as const;
