/**
 * The sitemap gate: every built page is listed, or deliberately is not.
 *
 * `/sitemap.xml` is written by hand (`src/pages/sitemap.xml.ts`) rather than
 * generated by an integration, which buys one file and no redirects and costs
 * exactly one thing: a new page can be added and nobody notices it never
 * reached the sitemap. This is that one thing, checked.
 *
 * Runs after a build, in `npm run verify`.
 */
import { readdirSync, statSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const BUILD = 'dist';

/** Pages that belong outside the sitemap. Mirrors EXCLUDED in the route. */
const EXCLUDED = [
  '/404',
  '/styleguide/',
  '/contatti/messaggio-inviato/',
  '/iscrizioni/grazie/',
  '/keystatic',
];

function pages(dir, prefix = '/', found = []) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) pages(path, `${prefix}${name}/`, found);
    else if (name === 'index.html') found.push(prefix);
    else if (name.endsWith('.html'))
      found.push(`${prefix}${name.replace(/\.html$/, '')}`);
  }
  return found;
}

if (!existsSync(`${BUILD}/sitemap.xml`)) {
  console.error('✗ no dist/sitemap.xml. Run `npm run build` first.');
  process.exit(1);
}

const sitemap = readFileSync(`${BUILD}/sitemap.xml`, 'utf8');
const listed = new Set(
  [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => new URL(m[1]).pathname),
);

let failed = false;
const built = pages(BUILD).sort();

for (const page of built) {
  if (listed.has(page)) continue;
  if (EXCLUDED.some((excluded) => page.startsWith(excluded))) continue;
  console.error(`✗ ${page} is built and is not in the sitemap.`);
  console.error('  Add it to src/pages/sitemap.xml.ts, or to EXCLUDED in both files.');
  failed = true;
}

/* And the other way: a sitemap entry with no page behind it is a 404 in a feed. */
for (const path of listed) {
  if (!built.includes(path)) {
    console.error(`✗ the sitemap lists ${path}, which the build did not write.`);
    failed = true;
  }
}

if (!failed) {
  console.log(
    `✓ sitemap lists every page  (${listed.size} listed, ${built.length} built)`,
  );
}

process.exit(failed ? 1 : 0);
